name: anaconda.enterprise.mlops.sdk
channels:
  - defaults
dependencies:
  - anaconda-client=1.11.0
  - attrs=22.1.0
  - beautifulsoup4=4.11.1
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2022.10.11
  - cctools=949.0.1
  - certifi=2022.9.24
  - cffi=1.15.1
  - chardet=4.0.0
  - clyent=1.2.2
  - conda=22.11.1
  - conda-build=3.23.3
  - conda-package-handling=1.9.0
  - cryptography=38.0.1
  - cython=0.29.32
  - filelock=3.6.0
  - glob2=0.7
  - icu=68.1
  - idna=3.4
  - jupyter_core=4.11.2
  - ld64
  - libarchive=3.6.1
  - libcxx=14.0.6
  - libffi=3.4.2
  - libiconv=1.16
  - liblief=0.12.3
  - libllvm14=14.0.6
  - libxml2=2.9.14
  - lz4-c=1.9.4
  - nbformat=5.7.0
  - ncurses=6.3
  - openssl=1.1.1s
  - patch=2.7.6
  - pip=22.3.1
  - pkginfo=1.8.3
  - pluggy=1.0.0
  - py-lief=0.12.3
  - pycosat=0.6.4
  - pycparser=2.21
  - pyopenssl=22.0.0
  - pysocks=1.7.1
  - python=3.10.8
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.16.2
  - python-libarchive-c=2.9
  - pyyaml=6.0
  - readline=8.2
  - requests=2.28.1
  - ruamel.yaml=0.17.21
  - ruamel.yaml.clib=0.2.6
  - setuptools=65.5.0
  - six=1.16.0
  - soupsieve=2.3.2.post1
  - sqlite=3.40.0
  - tapi=1100.0.11
  - tk=8.6.12
  - toml=0.10.2
  - toolz=0.12.0
  - tqdm=4.64.1
  - tzdata=2022g
  - urllib3=1.26.13
  - wheel=0.37.1
  - xz=5.2.8
  - yaml=0.2.5
  - zlib=1.2.13
  - zstd=1.5.2
  - pip:
      - alembic==1.8.1
      - anyio==3.6.2
      - appnope==0.1.3
      - argon2-cffi==21.3.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.2.3
      - astroid==2.12.13
      - asttokens==2.2.1
      - backcall==0.2.0
      - black==22.12.0
      - bleach==5.0.1
      - charset-normalizer==2.1.1
      - click==8.1.3
      - cloudpickle==2.2.0
      - comm==0.1.2
      - contourpy==1.0.6
      - coverage==6.5.0
      - cycler==0.11.0
      - databricks-cli==0.17.4
      - debugpy==1.6.4
      - decorator==5.1.1
      - defusedxml==0.7.1
      - dill==0.3.6
      - docker==6.0.1
      - entrypoints==0.4
      - executing==1.2.0
      - flask==2.2.2
      - fonttools==4.38.0
      - fqdn==1.5.1
      - gitdb==4.0.10
      - gitpython==3.1.29
      - gunicorn==20.1.0
      - importlib-metadata==5.1.0
      - ipykernel==6.19.2
      - ipython==8.7.0
      - ipython-genutils==0.2.0
      - ipywidgets==8.0.3
      - isoduration==20.11.0
      - isort==5.11.2
      - itsdangerous==2.1.2
      - jedi==0.18.2
      - jinja2==3.1.2
      - joblib==1.2.0
      - jsonpointer==2.3
      - jsonschema==4.17.3
      - jupyter==1.0.0
      - jupyter-client==7.4.8
      - jupyter-console==6.4.4
      - jupyter-core==5.1.0
      - jupyter-events==0.5.0
      - jupyter-server==2.0.1
      - jupyter-server-terminals==0.4.2
      - jupyterlab-pygments==0.2.2
      - jupyterlab-widgets==3.0.4
      - kiwisolver==1.4.4
      - lazy-object-proxy==1.8.0
      - llvmlite==0.39.1
      - mako==1.2.4
      - markdown==3.4.1
      - markupsafe==2.1.1
      - matplotlib==3.6.2
      - matplotlib-inline==0.1.6
      - mccabe==0.7.0
      - mistune==2.0.4
      - mlflow==2.0.1
      - mypy-extensions==0.4.3
      - nbclassic==0.4.8
      - nbclient==0.7.2
      - nbconvert==7.2.6
      - nest-asyncio==1.5.6
      - notebook==6.5.2
      - notebook-shim==0.2.2
      - numba==0.56.4
      - numpy==1.23.5
      - oauthlib==3.2.2
      - packaging==21.3
      - pandas==1.5.2
      - pandocfilters==1.5.0
      - parso==0.8.3
      - pathspec==0.10.3
      - pexpect==4.8.0
      - pickleshare==0.7.5
      - pillow==9.3.0
      - platformdirs==2.6.0
      - prometheus-client==0.15.0
      - prompt-toolkit==3.0.36
      - protobuf==4.21.11
      - psutil==5.9.4
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - pyarrow==10.0.1
      - pydantic==1.10.2
      - pygments==2.13.0
      - pyjwt==2.6.0
      - pylint==2.15.8
      - pyparsing==3.0.9
      - pyrsistent==0.19.2
      - python-dotenv==0.21.0
      - python-json-logger==2.0.4
      - pytz==2022.6
      - pyzmq==24.0.1
      - qtconsole==5.4.0
      - qtpy==2.3.0
      - querystring-parser==1.2.4
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - sacr==1.0.0
      - scikit-learn==1.2.0
      - scipy==1.9.3
      - send2trash==1.8.0
      - shap==0.41.0
      - slicer==0.0.7
      - smmap==5.0.0
      - sniffio==1.3.0
      - sqlalchemy==1.4.45
      - sqlparse==0.4.3
      - stack-data==0.6.2
      - tabulate==0.9.0
      - terminado==0.17.1
      - threadpoolctl==3.1.0
      - tinycss2==1.2.1
      - tokenize-rt==5.0.0
      - tomli==2.0.1
      - tomlkit==0.11.6
      - tornado==6.2
      - traitlets==5.7.1
      - typing-extensions==4.4.0
      - uri-template==1.2.0
      - wcwidth==0.2.5
      - webcolors==1.12
      - webencodings==0.5.1
      - websocket-client==1.4.2
      - werkzeug==2.2.2
      - widgetsnbextension==4.0.4
      - wrapt==1.14.1
      - zipp==3.11.0
