name: anaconda.enterprise.mlops.sdk
channels:
  - defaults
  - conda-forge
  - joshburt
dependencies:
  - python=3.10.8
  - mlflow=2.0.1
  - black
  - conda-build
  - black-jupyter
  - jupyter
  - coverage
  - isort
  - pydantic
  - pylint
  - python-dotenv
  - setuptools
  - anaconda-client
  - shapeandshare.command.runner
  - anaconda.enterprise.server.common.sdk
  - anaconda.enterprise.server.contracts
