name: anaconda.enterprise.mlops.sdk
channels:
  - defaults
  - conda-forge
dependencies:
  - alembic=1.8.1
  - arrow-cpp=10.0.1
  - astroid=2.11.7
  - aws-c-auth=0.6.21
  - aws-c-cal=0.5.20
  - aws-c-common=0.8.5
  - aws-c-compression=0.2.16
  - aws-c-event-stream=0.2.15
  - aws-c-http=0.6.27
  - aws-c-io=0.13.11
  - aws-c-mqtt=0.7.13
  - aws-c-s3=0.2.1
  - aws-c-sdkutils=0.1.7
  - aws-checksums=0.1.14
  - aws-crt-cpp=0.18.16
  - aws-sdk-cpp=1.9.379
  - bcrypt=3.2.2
  - beautifulsoup4=4.11.1
  - black=22.6.0
  - blinker=1.5
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2022.10.11
  - cctools=949.0.1
  - cctools_osx-arm64=949.0.1
  - certifi=2022.9.24
  - cffi=1.15.1
  - chardet=4.0.0
  - charset-normalizer=2.1.1
  - click=8.1.3
  - cloudpickle=2.2.0
  - colorama=0.4.6
  - conda=22.11.1
  - conda-build=3.23.3
  - conda-package-handling=1.9.0
  - configparser=5.3.0
  - contourpy=1.0.6
  - coverage=6.3.2
  - cryptography=38.0.4
  - cycler=0.11.0
  - databricks-cli=0.17.4
  - dill=0.3.6
  - docker-py=6.0.0
  - entrypoints=0.4
  - filelock=3.6.0
  - flask=2.2.2
  - fonttools=4.38.0
  - freetype=2.12.1
  - gflags=2.2.2
  - gitdb=4.0.10
  - gitpython=3.1.29
  - glob2=0.7
  - glog=0.6.0
  - greenlet=2.0.1
  - gunicorn=20.1.0
  - icu=68.1
  - idna=3.4
  - importlib-metadata=5.1.0
  - importlib_resources=5.10.1
  - isort=5.9.3
  - itsdangerous=2.1.2
  - jinja2=3.1.2
  - joblib=1.2.0
  - jpeg=9e
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lazy-object-proxy=1.6.0
  - lcms2=2.14
  - ld64=530
  - ld64_osx-arm64=530
  - ldid=2.1.2
  - lerc=4.0.0
  - libabseil=20220623.0
  - libarchive=3.6.1
  - libarrow=10.0.1
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libcrc32c=1.1.2
  - libcurl=7.86.0
  - libcxx=14.0.6
  - libdeflate=1.14
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.10
  - libffi=3.4.2
#  - libgfortran=5.0.0
  - libgfortran5=11.3.0
  - libgoogle-cloud=2.5.0
  - libgrpc=1.51.1
  - libiconv=1.16
  - liblapack=3.9.0
  - liblief=0.12.3
  - libllvm11=11.1.0
  - libllvm14=14.0.6
  - libnghttp2=1.47.0
  - libopenblas=0.3.21
  - libpng=1.6.39
  - libprotobuf=3.21.11
  - libsodium=1.0.18
  - libsqlite=3.40.0
  - libssh2=1.10.0
  - libthrift=0.16.0
  - libtiff=4.4.0
  - libutf8proc=2.8.0
  - libwebp-base=1.2.4
  - libxcb=1.13
  - libxml2=2.9.14
  - libzlib=1.2.13
  - llvm-openmp=15.0.6
  - llvmlite=0.39.1
  - lz4-c=1.9.3
  - mako=1.2.4
  - markdown=3.4.1
  - markupsafe=2.1.1
  - matplotlib-base=3.6.2
  - mccabe=0.7.0
  - mlflow=2.0.1
  - munkres=1.1.4
  - mypy_extensions=0.4.3
  - ncurses=6.3
  - numba=0.56.4
  - numpy=1.23.5
  - oauthlib=3.2.2
  - openjpeg=2.5.0
  - openssl=3.0.7
  - orc=1.8.1
  - packaging=21.3
  - pandas=1.5.2
  - paramiko=2.12.0
  - parquet-cpp=1.5.1
  - patch=2.7.6
  - pathspec=0.9.0
  - pillow=9.2.0
  - pip=22.3.1
  - pkginfo=1.8.3
  - platformdirs=2.5.2
  - pluggy=1.0.0
  - prometheus_client=0.15.0
  - prometheus_flask_exporter=0.21.0
  - protobuf=4.21.11
  - psutil=5.9.0
  - pthread-stubs=0.4
  - py-lief=0.12.3
  - pyarrow=10.0.1
  - pycosat=0.6.4
  - pycparser=2.21
  - pydantic=1.10.2
  - pyjwt=2.6.0
  - pylint=2.14.5
  - pynacl=1.5.0
  - pyopenssl=22.1.0
  - pyparsing=3.0.9
  - pysocks=1.7.1
  - python=3.10.8
  - python-dateutil=2.8.2
  - python-dotenv=0.21.0
  - python-libarchive-c=2.9
  - python_abi=3.10
  - pytz=2022.6
  - pywin32-on-windows=0.1.0
  - pyyaml=6.0
  - querystring_parser=1.2.4
  - re2=2022.06.01
  - readline=8.1.2
  - requests=2.28.1
  - ripgrep=13.0.0
  - ruamel.yaml=0.17.21
  - ruamel.yaml.clib=0.2.6
  - scikit-learn=1.2.0
  - scipy=1.9.3
  - setuptools=65.5.1
  - shap=0.41.0
  - six=1.16.0
  - slicer=0.0.7
  - smmap=3.0.5
  - snappy=1.1.9
  - soupsieve=2.3.2.post1
  - sqlalchemy=1.4.45
  - sqlite=3.40.0
  - sqlparse=0.4.3
  - tabulate=0.9.0
  - tapi=1100.0.11
  - threadpoolctl=3.1.0
  - tk=8.6.12
  - toml=0.10.2
  - tomli=2.0.1
  - tomlkit=0.11.1
  - toolz=0.12.0
  - tqdm=4.64.1
  - typing-extensions=4.4.0
  - typing_extensions=4.4.0
  - tzdata=2022g
  - unicodedata2=15.0.0
  - urllib3=1.26.13
  - websocket-client=1.4.2
  - werkzeug=2.2.2
  - wheel=0.38.4
  - wrapt=1.14.1
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xz=5.2.6
  - yaml=0.2.5
  - zipp=3.11.0
  - zlib=1.2.13
  - zstd=1.5.2
  - pip:
    - sacr==1.0.0
