name: anaconda.enterprise.mlops.sdk
channels:
  - defaults
  - conda-forge
dependencies:
  - black
  - conda-build
  - coverage
  - isort
  - pylint
  - mlflow=2.0.1
  - pip
  - python=3.10.8
  - setuptools
  - anaconda-client
  - python-dotenv
  - pydantic
  - pip:
    - sacr
