name: anaconda.enterprise.mlops.sdk
channels:
  - defaults
dependencies:
  - python=3.10.8
  - anaconda-client
  - conda-build
  - pip:
      - black
      - coverage
      - isort
      - jupyter==1.0.0
      - mlflow==2.0.1
      - pylint
      - python-dotenv
      - sacr==1.0.0
