{% set name = "anaconda.enterprise.mlops.sdk" %}
{% set version = "0.2.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  path: ../

build:
  number: 0
  noarch: python
  script:
    - {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv

requirements:
  host:
    - python>=3.9
    - setuptools
  run:
    - python>=3.9
    - mlflow>=2.0.1
    - anaconda.enterprise.server.common.sdk
    - anaconda.enterprise.server.contracts

about:
  home: https://github.com/shapeandshare/anaconda.enterprise.mlops.sdk
  summary: "Anaconda Enterprise MLOps SDK"
  license: BSD
  license_file: LICENSE
